baseURL = 'https://ceruulean.github.io/cvage/'
languageCode = 'en-us'
title = 'Diana Wu'
theme = 'simplenote'
description = '進める'
canonifyURLs = true



sectionPagesMenu = 'portfolio'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
